# -*- coding: utf-8 -*-
"""modul_penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QfX0Mlk9KmvmPVjotCtw_Ma5kHyYfHQa
"""

def penjumlahan(angka_1, angka_2):
  jumlah = angka_1 + angka_2
  return jumlah